name: Auto Approve Environment Deployments
description: Retrieve environment ID and auto-approve pending deployments in GitHub Actions.
branding:
  icon: check-circle
  color: green
inputs:
  environment:
    description: The name of the environment.
    required: true
  token:
    description: GitHub personal-acess token for API access. Requires read permissions on environments and read/write permissions on actions.
    required: true
runs:
  using: "composite"
  steps:
    - name: Get Environment ID
      id: environment-id
      shell: pwsh
      run: |
        $environmentId = ""
        $url = "https://api.github.com/repos/${{ github.repository }}/environments"
        $response = Invoke-RestMethod -Uri $url -Method Get -Headers @{
          Authorization = "Bearer ${{ inputs.token }}"
        }
        if ($response) {
          foreach ($environment in $response.environments) {
            if ($environment.name -eq "${{ inputs.environment }}") {
              $environmentId = $environment.id
              break
            }
          }
        }
        echo "Found environment id: $($environmentId)"
        echo "environment_id=$($environmentId)" >> $env:GITHUB_OUTPUT

    - name: Wait 1s
      shell: pwsh
      run: |
        Start-Sleep -Seconds 1

    - name: Auto Approve Deployment
      shell: pwsh
      run: |
        $url = "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/pending_deployments"
        $body = @"
        {
          "environment_ids": [ ${{ steps.environment-id.outputs.environment_id }} ],
          "state": "approved",
          "comment": "Auto-approved for automation"
        }
        "@
        Write-Host "Making request to: $url"
        Write-Host "Request body: $body"
        try {
          $response = Invoke-RestMethod -Uri $url -Method POST -Headers @{
            Authorization = "Bearer ${{ inputs.token }}"
          } -Body $body -ContentType "application/json"
          Write-Host "✅ Successfully approved pending deployments"
          Write-Host "Response: $($response | ConvertTo-Json -Depth 10)"
        }
        catch {
          $statusCode = $_.Exception.Response.StatusCode.value__
          Write-Host "❌ Request failed with status code: $statusCode"
          
          # Try to get error response body
          try {
            $errorResponse = $_.ErrorDetails.Message
            if ($errorResponse) {
              Write-Host "Error response body: $errorResponse"
            }
          }
          catch {
            Write-Host "Could not retrieve error response body"
          }
          
          Write-Host "Full error: $($_.Exception.Message)"
          if ($statusCode -eq 422) {
            Write-Host "ℹ️ No pending deployments found to approve"
            exit 0
          }
          else {
            throw
          }
        }
