name: Auto Approve Environment Deployments
description: Retrieve environment ID and auto-approve pending deployments in GitHub Actions.
branding:
  icon: check-circle
  color: green
inputs:
  environment:
    description: The name of the environment.
    required: true
  token:
    description: GitHub personal-acess token for API access. Requires read permissions on environments and read/write permissions on actions.
    required: true
runs:
  using: "composite"
  steps:
    - name: Get Environment ID
      id: environment-id
      shell: pwsh
      run: |
        $environmentId = ""
        $url = "https://api.github.com/repos/${{ github.repository }}/environments"
        $response = Invoke-RestMethod -Uri $url -Method Get -Headers @{
          Authorization = "Bearer ${{ inputs.token }}"
        }
        if ($response) {
          foreach ($environment in $response.environments) {
            if ($environment.name -eq "${{ inputs.environment }}") {
              $environmentId = $environment.id
              break
            }
          }
        }
        echo "environment_id=$($environmentId)" >> $env:GITHUB_OUTPUT

    - name: Auto Approve Deployment
      shell: pwsh
      run: |
        $url = "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/pending_deployments"
        $body = @"
        {
          "environment_ids": [ ${{ steps.environment-id.outputs.environment_id }} ],
          "state": "approved",
          "comment": "Auto-approved for automation"
        }
        "@
        try {
          Invoke-RestMethod -Uri $url -Method POST -Headers @{
            Authorization = "Bearer ${{ inputs.token }}"
          } -Body $body -ContentType "application/json"
          Write-Host "Deployment approved successfully"
        }
        catch {
          $errorMessage = $_.Exception.Message
          
          if ($errorMessage -like "*No pending deployment*") {
            Write-Host "No pending deployments found."
            exit 0
          }
          else {
            Write-Error "Failed to approve deployment: $errorMessage"
            throw
          }
        }
